version: '3.8'
services:
  tomcat:
    env_file:
      - ./.env
    image: tomcat:latest
    container_name: WS__${PROJECT_NAME}
    ports:
      - ${PROJECT_PORT}:8080
    volumes:
      - ./src:/usr/local/tomcat/webapps/ROOT
    external_links:
      - DB__workwp:mariadb

networks:
  default:
    external:
      name: db_work
